name: Deploy to EC2

on:
  push:
    branches: [ feature/payment ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            docker pull kingsleychino/demo-app:1.0
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 8080:8080 kingsleychino/demo-app:1.0
            echo "Deployment complete"
